### ISSUE TITLE
test.run doesn't return a promise with asynchronous tests

### ISSUE THREAD

**Issue by lovasoa** [Gozala/test-commonjs#9]
The following code raises an error:

``` javascript
require("test").run({
  test: function(assert, end){
    setTimeout(end, 0);
  }
}).then(function(){});
```

The error is:

```
/tmp/bugtest/test.js:7
}).then(function(){});
   ^
TypeError: Cannot call method 'then' of undefined
    at Object.<anonymous> (/tmp/bugtest/test.js:7:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

**Comment by Gozala** [comment]
Indeed `run` does not return promise, but it's not a bug. That could be implemented, but given low interest in this package I can't justify an effort it would take. If anyone wants to implement it, I'll take a pr.
